/**
 * shared/amounts.test.ts — the timing helpers and the scaling round-off.
 *
 * `formatMinutes` and `stepMinutes` exist to survive input the layout and
 * sequence fixtures never carry.
 * `minutes` is a box a person types into and a field `validateRecipe` has no
 * opinion on, so it is the one number in a stored recipe that can be any
 * shape at all by the time it reaches a render.
 */

import test from "node:test";
import assert from "node:assert/strict";
import {
  editableAmount,
  formatAmount,
  formatMinutes,
  snapQty,
  stepMinutes,
} from "./amounts";
import { parseAmount } from "./edits";
import type { Ingredient, Unit } from "./layout";

test("formatMinutes renders minutes and hours", () => {
  assert.equal(formatMinutes(12), "12 min");
  assert.equal(formatMinutes(59), "59 min");
  assert.equal(formatMinutes(60), "1 hr");
  assert.equal(formatMinutes(90), "1 hr 30 min");
  assert.equal(formatMinutes(125), "2 hr 5 min");
  // Fractions are typeable ("1 1/2"), so they must not render as "1.5 min".
  assert.equal(formatMinutes(1.5), "2 min");
});

test("formatMinutes returns null for anything that is not a usable number", () => {
  // The failure this exists for: "12 min" is truthy, so every caller's
  // `step.minutes ? …` test passed it straight into `min < 60`.
  assert.equal(formatMinutes("12 min"), null);
  assert.equal(formatMinutes("12"), null);
  assert.equal(formatMinutes(null), null);
  assert.equal(formatMinutes(undefined), null);
  assert.equal(formatMinutes(0), null);
  assert.equal(formatMinutes(-5), null);
  assert.equal(formatMinutes(NaN), null);
  assert.equal(formatMinutes(Infinity), null);
});

test("stepMinutes is the same guard as a number, for the timer's arithmetic", () => {
  assert.equal(stepMinutes(12), 12);
  assert.equal(stepMinutes(1.5), 1.5);
  assert.equal(stepMinutes("12 min"), null);
  assert.equal(stepMinutes(0), null);
  assert.equal(stepMinutes(NaN), null);
  // The bug in one line: this used to be NaN, and a NaN endsAt renders a
  // countdown of "NaN:NaN" that never elapses.
  assert.ok(Number.isFinite(Date.parse("2020-01-01") + (stepMinutes("12 min") ?? 0) * 60_000));
});

// ---------------------------------------------------------------------------
// Unit-aware rounding of scaled amounts.
// ---------------------------------------------------------------------------

const ing = (qty: number | null, unit: Unit | null, qtyMax?: number | null): Ingredient =>
  ({ id: "i", qty, qtyMax: qtyMax ?? null, unit, name: "thing" });

/**
 * THE REGRESSION THAT MATTERS MOST.
 *
 * Every row was generated by running the PRE-ROUNDING implementation and then
 * pasted here as a literal — so this table cannot drift with the code it
 * guards. An unscaled recipe having its amounts quietly rewritten on screen
 * would be worse than any rounding error on a scaled one, and this is the only
 * thing standing between that and a release.
 *
 * If you change rendering and these fail, the answer is almost never to
 * regenerate the table.
 */
const FROZEN_AT_SCALE_1: Array<[number, number | null, Unit | null, string]> = [
  [1, null, "g", "1 g"],
  [1, null, "kg", "1 kg"],
  [1, null, "oz", "1 oz"],
  [1, null, "lb", "1 lb"],
  [1, null, "ml", "1 ml"],
  [1, null, "l", "1 l"],
  [1, null, "tsp", "1 tsp"],
  [1, null, "tbsp", "1 Tbs"],
  [1, null, "cup", "1 cup"],
  [1, null, "fl_oz", "1 fl oz"],
  [1, null, "pinch", "1 pinch"],
  [1, null, null, "1"],
  [2, null, "g", "2 g"],
  [2, null, "kg", "2 kg"],
  [2, null, "oz", "2 oz"],
  [2, null, "lb", "2 lb"],
  [2, null, "ml", "2 ml"],
  [2, null, "l", "2 l"],
  [2, null, "tsp", "2 tsp"],
  [2, null, "tbsp", "2 Tbs"],
  [2, null, "cup", "2 cup"],
  [2, null, "fl_oz", "2 fl oz"],
  [2, null, "pinch", "2 pinch"],
  [2, null, null, "2"],
  [3, null, "g", "3 g"],
  [3, null, "kg", "3 kg"],
  [3, null, "oz", "3 oz"],
  [3, null, "lb", "3 lb"],
  [3, null, "ml", "3 ml"],
  [3, null, "l", "3 l"],
  [3, null, "tsp", "3 tsp"],
  [3, null, "tbsp", "3 Tbs"],
  [3, null, "cup", "3 cup"],
  [3, null, "fl_oz", "3 fl oz"],
  [3, null, "pinch", "3 pinch"],
  [3, null, null, "3"],
  [12, null, "g", "12 g"],
  [12, null, "kg", "12 kg"],
  [12, null, "oz", "12 oz"],
  [12, null, "lb", "12 lb"],
  [12, null, "ml", "12 ml"],
  [12, null, "l", "12 l"],
  [12, null, "tsp", "12 tsp"],
  [12, null, "tbsp", "12 Tbs"],
  [12, null, "cup", "12 cup"],
  [12, null, "fl_oz", "12 fl oz"],
  [12, null, "pinch", "12 pinch"],
  [12, null, null, "12"],
  [0.5, null, "g", "½ g"],
  [0.5, null, "kg", "½ kg"],
  [0.5, null, "oz", "½ oz"],
  [0.5, null, "lb", "½ lb"],
  [0.5, null, "ml", "½ ml"],
  [0.5, null, "l", "½ l"],
  [0.5, null, "tsp", "½ tsp"],
  [0.5, null, "tbsp", "½ Tbs"],
  [0.5, null, "cup", "½ cup"],
  [0.5, null, "fl_oz", "½ fl oz"],
  [0.5, null, "pinch", "½ pinch"],
  [0.5, null, null, "½"],
  [0.25, null, "g", "¼ g"],
  [0.25, null, "kg", "¼ kg"],
  [0.25, null, "oz", "¼ oz"],
  [0.25, null, "lb", "¼ lb"],
  [0.25, null, "ml", "¼ ml"],
  [0.25, null, "l", "¼ l"],
  [0.25, null, "tsp", "¼ tsp"],
  [0.25, null, "tbsp", "¼ Tbs"],
  [0.25, null, "cup", "¼ cup"],
  [0.25, null, "fl_oz", "¼ fl oz"],
  [0.25, null, "pinch", "¼ pinch"],
  [0.25, null, null, "¼"],
  [1.5, null, "g", "1½ g"],
  [1.5, null, "kg", "1½ kg"],
  [1.5, null, "oz", "1½ oz"],
  [1.5, null, "lb", "1½ lb"],
  [1.5, null, "ml", "1½ ml"],
  [1.5, null, "l", "1½ l"],
  [1.5, null, "tsp", "1½ tsp"],
  [1.5, null, "tbsp", "1½ Tbs"],
  [1.5, null, "cup", "1½ cup"],
  [1.5, null, "fl_oz", "1½ fl oz"],
  [1.5, null, "pinch", "1½ pinch"],
  [1.5, null, null, "1½"],
  [2.5, null, "g", "2½ g"],
  [2.5, null, "kg", "2½ kg"],
  [2.5, null, "oz", "2½ oz"],
  [2.5, null, "lb", "2½ lb"],
  [2.5, null, "ml", "2½ ml"],
  [2.5, null, "l", "2½ l"],
  [2.5, null, "tsp", "2½ tsp"],
  [2.5, null, "tbsp", "2½ Tbs"],
  [2.5, null, "cup", "2½ cup"],
  [2.5, null, "fl_oz", "2½ fl oz"],
  [2.5, null, "pinch", "2½ pinch"],
  [2.5, null, null, "2½"],
  [0.125, null, "g", "⅛ g"],
  [0.125, null, "kg", "⅛ kg"],
  [0.125, null, "oz", "⅛ oz"],
  [0.125, null, "lb", "⅛ lb"],
  [0.125, null, "ml", "⅛ ml"],
  [0.125, null, "l", "⅛ l"],
  [0.125, null, "tsp", "⅛ tsp"],
  [0.125, null, "tbsp", "⅛ Tbs"],
  [0.125, null, "cup", "⅛ cup"],
  [0.125, null, "fl_oz", "⅛ fl oz"],
  [0.125, null, "pinch", "⅛ pinch"],
  [0.125, null, null, "⅛"],
  [0.375, null, "g", "⅜ g"],
  [0.375, null, "kg", "⅜ kg"],
  [0.375, null, "oz", "⅜ oz"],
  [0.375, null, "lb", "⅜ lb"],
  [0.375, null, "ml", "⅜ ml"],
  [0.375, null, "l", "⅜ l"],
  [0.375, null, "tsp", "⅜ tsp"],
  [0.375, null, "tbsp", "⅜ Tbs"],
  [0.375, null, "cup", "⅜ cup"],
  [0.375, null, "fl_oz", "⅜ fl oz"],
  [0.375, null, "pinch", "⅜ pinch"],
  [0.375, null, null, "⅜"],
  [0.75, null, "g", "¾ g"],
  [0.75, null, "kg", "¾ kg"],
  [0.75, null, "oz", "¾ oz"],
  [0.75, null, "lb", "¾ lb"],
  [0.75, null, "ml", "¾ ml"],
  [0.75, null, "l", "¾ l"],
  [0.75, null, "tsp", "¾ tsp"],
  [0.75, null, "tbsp", "¾ Tbs"],
  [0.75, null, "cup", "¾ cup"],
  [0.75, null, "fl_oz", "¾ fl oz"],
  [0.75, null, "pinch", "¾ pinch"],
  [0.75, null, null, "¾"],
  [2.25, null, "g", "2¼ g"],
  [2.25, null, "kg", "2¼ kg"],
  [2.25, null, "oz", "2¼ oz"],
  [2.25, null, "lb", "2¼ lb"],
  [2.25, null, "ml", "2¼ ml"],
  [2.25, null, "l", "2¼ l"],
  [2.25, null, "tsp", "2¼ tsp"],
  [2.25, null, "tbsp", "2¼ Tbs"],
  [2.25, null, "cup", "2¼ cup"],
  [2.25, null, "fl_oz", "2¼ fl oz"],
  [2.25, null, "pinch", "2¼ pinch"],
  [2.25, null, null, "2¼"],
  [1 / 3, null, "g", "⅓ g"],
  [1 / 3, null, "kg", "⅓ kg"],
  [1 / 3, null, "oz", "⅓ oz"],
  [1 / 3, null, "lb", "⅓ lb"],
  [1 / 3, null, "ml", "⅓ ml"],
  [1 / 3, null, "l", "⅓ l"],
  [1 / 3, null, "tsp", "⅓ tsp"],
  [1 / 3, null, "tbsp", "⅓ Tbs"],
  [1 / 3, null, "cup", "⅓ cup"],
  [1 / 3, null, "fl_oz", "⅓ fl oz"],
  [1 / 3, null, "pinch", "⅓ pinch"],
  [1 / 3, null, null, "⅓"],
  [2 / 3, null, "g", "⅔ g"],
  [2 / 3, null, "kg", "⅔ kg"],
  [2 / 3, null, "oz", "⅔ oz"],
  [2 / 3, null, "lb", "⅔ lb"],
  [2 / 3, null, "ml", "⅔ ml"],
  [2 / 3, null, "l", "⅔ l"],
  [2 / 3, null, "tsp", "⅔ tsp"],
  [2 / 3, null, "tbsp", "⅔ Tbs"],
  [2 / 3, null, "cup", "⅔ cup"],
  [2 / 3, null, "fl_oz", "⅔ fl oz"],
  [2 / 3, null, "pinch", "⅔ pinch"],
  [2 / 3, null, null, "⅔"],
  [1.37, null, "g", "1⅜ g"],
  [1.37, null, "kg", "1⅜ kg"],
  [1.37, null, "oz", "1⅜ oz"],
  [1.37, null, "lb", "1⅜ lb"],
  [1.37, null, "ml", "1⅜ ml"],
  [1.37, null, "l", "1⅜ l"],
  [1.37, null, "tsp", "1⅜ tsp"],
  [1.37, null, "tbsp", "1⅜ Tbs"],
  [1.37, null, "cup", "1⅜ cup"],
  [1.37, null, "fl_oz", "1⅜ fl oz"],
  [1.37, null, "pinch", "1⅜ pinch"],
  [1.37, null, null, "1⅜"],
  [2.8125, null, "g", "2.81 g"],
  [2.8125, null, "kg", "2.81 kg"],
  [2.8125, null, "oz", "2.81 oz"],
  [2.8125, null, "lb", "2.81 lb"],
  [2.8125, null, "ml", "2.81 ml"],
  [2.8125, null, "l", "2.81 l"],
  [2.8125, null, "tsp", "2.81 tsp"],
  [2.8125, null, "tbsp", "2.81 Tbs"],
  [2.8125, null, "cup", "2.81 cup"],
  [2.8125, null, "fl_oz", "2.81 fl oz"],
  [2.8125, null, "pinch", "2.81 pinch"],
  [2.8125, null, null, "2.81"],
  [0.3, null, "g", "0.3 g"],
  [0.3, null, "kg", "0.3 kg"],
  [0.3, null, "oz", "0.3 oz"],
  [0.3, null, "lb", "0.3 lb"],
  [0.3, null, "ml", "0.3 ml"],
  [0.3, null, "l", "0.3 l"],
  [0.3, null, "tsp", "0.3 tsp"],
  [0.3, null, "tbsp", "0.3 Tbs"],
  [0.3, null, "cup", "0.3 cup"],
  [0.3, null, "fl_oz", "0.3 fl oz"],
  [0.3, null, "pinch", "0.3 pinch"],
  [0.3, null, null, "0.3"],
  [7.5, null, "g", "7½ g"],
  [7.5, null, "kg", "7½ kg"],
  [7.5, null, "oz", "7½ oz"],
  [7.5, null, "lb", "7½ lb"],
  [7.5, null, "ml", "7½ ml"],
  [7.5, null, "l", "7½ l"],
  [7.5, null, "tsp", "7½ tsp"],
  [7.5, null, "tbsp", "7½ Tbs"],
  [7.5, null, "cup", "7½ cup"],
  [7.5, null, "fl_oz", "7½ fl oz"],
  [7.5, null, "pinch", "7½ pinch"],
  [7.5, null, null, "7½"],
  [240, null, "g", "240 g"],
  [240, null, "kg", "240 kg"],
  [240, null, "oz", "240 oz"],
  [240, null, "lb", "240 lb"],
  [240, null, "ml", "240 ml"],
  [240, null, "l", "240 l"],
  [240, null, "tsp", "240 tsp"],
  [240, null, "tbsp", "240 Tbs"],
  [240, null, "cup", "240 cup"],
  [240, null, "fl_oz", "240 fl oz"],
  [240, null, "pinch", "240 pinch"],
  [240, null, null, "240"],
  [133.3, null, "g", "133.3 g"],
  [133.3, null, "kg", "133.3 kg"],
  [133.3, null, "oz", "133.3 oz"],
  [133.3, null, "lb", "133.3 lb"],
  [133.3, null, "ml", "133.3 ml"],
  [133.3, null, "l", "133.3 l"],
  [133.3, null, "tsp", "133.3 tsp"],
  [133.3, null, "tbsp", "133.3 Tbs"],
  [133.3, null, "cup", "133.3 cup"],
  [133.3, null, "fl_oz", "133.3 fl oz"],
  [133.3, null, "pinch", "133.3 pinch"],
  [133.3, null, null, "133.3"],
  [1.1, null, "g", "1.1 g"],
  [1.1, null, "kg", "1.1 kg"],
  [1.1, null, "oz", "1.1 oz"],
  [1.1, null, "lb", "1.1 lb"],
  [1.1, null, "ml", "1.1 ml"],
  [1.1, null, "l", "1.1 l"],
  [1.1, null, "tsp", "1.1 tsp"],
  [1.1, null, "tbsp", "1.1 Tbs"],
  [1.1, null, "cup", "1.1 cup"],
  [1.1, null, "fl_oz", "1.1 fl oz"],
  [1.1, null, "pinch", "1.1 pinch"],
  [1.1, null, null, "1.1"],
  [24, null, "g", "24 g"],
  [24, null, "kg", "24 kg"],
  [24, null, "oz", "24 oz"],
  [24, null, "lb", "24 lb"],
  [24, null, "ml", "24 ml"],
  [24, null, "l", "24 l"],
  [24, null, "tsp", "24 tsp"],
  [24, null, "tbsp", "24 Tbs"],
  [24, null, "cup", "24 cup"],
  [24, null, "fl_oz", "24 fl oz"],
  [24, null, "pinch", "24 pinch"],
  [24, null, null, "24"],
  [375, null, "g", "375 g"],
  [375, null, "kg", "375 kg"],
  [375, null, "oz", "375 oz"],
  [375, null, "lb", "375 lb"],
  [375, null, "ml", "375 ml"],
  [375, null, "l", "375 l"],
  [375, null, "tsp", "375 tsp"],
  [375, null, "tbsp", "375 Tbs"],
  [375, null, "cup", "375 cup"],
  [375, null, "fl_oz", "375 fl oz"],
  [375, null, "pinch", "375 pinch"],
  [375, null, null, "375"],
  [0.05, null, "g", "0.05 g"],
  [0.05, null, "kg", "0.05 kg"],
  [0.05, null, "oz", "0.05 oz"],
  [0.05, null, "lb", "0.05 lb"],
  [0.05, null, "ml", "0.05 ml"],
  [0.05, null, "l", "0.05 l"],
  [0.05, null, "tsp", "0.05 tsp"],
  [0.05, null, "tbsp", "0.05 Tbs"],
  [0.05, null, "cup", "0.05 cup"],
  [0.05, null, "fl_oz", "0.05 fl oz"],
  [0.05, null, "pinch", "0.05 pinch"],
  [0.05, null, null, "0.05"],
  [2, 3, "g", "2–3 g"],
  [2, 3, "kg", "2–3 kg"],
  [2, 3, "oz", "2–3 oz"],
  [2, 3, "lb", "2–3 lb"],
  [2, 3, "ml", "2–3 ml"],
  [2, 3, "l", "2–3 l"],
  [2, 3, "tsp", "2–3 tsp"],
  [2, 3, "tbsp", "2–3 Tbs"],
  [2, 3, "cup", "2–3 cup"],
  [2, 3, "fl_oz", "2–3 fl oz"],
  [2, 3, "pinch", "2–3 pinch"],
  [2, 3, null, "2–3"],
  [1.5, 2.5, "g", "1½–2½ g"],
  [1.5, 2.5, "kg", "1½–2½ kg"],
  [1.5, 2.5, "oz", "1½–2½ oz"],
  [1.5, 2.5, "lb", "1½–2½ lb"],
  [1.5, 2.5, "ml", "1½–2½ ml"],
  [1.5, 2.5, "l", "1½–2½ l"],
  [1.5, 2.5, "tsp", "1½–2½ tsp"],
  [1.5, 2.5, "tbsp", "1½–2½ Tbs"],
  [1.5, 2.5, "cup", "1½–2½ cup"],
  [1.5, 2.5, "fl_oz", "1½–2½ fl oz"],
  [1.5, 2.5, "pinch", "1½–2½ pinch"],
  [1.5, 2.5, null, "1½–2½"],
  [0.25, 0.5, "g", "¼–½ g"],
  [0.25, 0.5, "kg", "¼–½ kg"],
  [0.25, 0.5, "oz", "¼–½ oz"],
  [0.25, 0.5, "lb", "¼–½ lb"],
  [0.25, 0.5, "ml", "¼–½ ml"],
  [0.25, 0.5, "l", "¼–½ l"],
  [0.25, 0.5, "tsp", "¼–½ tsp"],
  [0.25, 0.5, "tbsp", "¼–½ Tbs"],
  [0.25, 0.5, "cup", "¼–½ cup"],
  [0.25, 0.5, "fl_oz", "¼–½ fl oz"],
  [0.25, 0.5, "pinch", "¼–½ pinch"],
  [0.25, 0.5, null, "¼–½"],
];

test("scale 1 renders byte-for-byte what was extracted, for every unit", () => {
  for (const [qty, qtyMax, unit, expected] of FROZEN_AT_SCALE_1) {
    const where = `${qty}${qtyMax != null ? `-${qtyMax}` : ""} ${unit ?? "(countable)"}`;
    assert.equal(formatAmount(ing(qty, unit, qtyMax), 1), expected, where);
    // The default argument is the same path — nothing renders unscaled by
    // accident of how its caller happens to be written.
    assert.equal(formatAmount(ing(qty, unit, qtyMax)), expected, where);
  }
});

test("the motivating case: 2¼ cup scaled by 1.25 is a measurable amount", () => {
  // 2.8125 cup. Nobody owns a 2.81-cup measure; this is the whole feature.
  assert.equal(formatAmount(ing(2.25, "cup"), 1.25), "2¾ cup");
});

test("each unit snaps to what its own measure can express", () => {
  // Spoons: eighths of a teaspoon, quarters of a tablespoon.
  assert.equal(snapQty(1.1, "tsp"), 1.125);
  assert.equal(snapQty(1.7, "tbsp"), 1.75);
  // Cups carry thirds as well as quarters, because every cup set has a ⅓.
  // Asserted as the rendered glyph rather than the number: a third is the one
  // rung that is not a binary fraction, so 10 * (1/3) and 10 / 3 are different
  // doubles and strict equality would be testing IEEE, not the ladder.
  assert.equal(formatAmount(ing(3, "cup"), 1.1), "3⅓ cup");
  assert.equal(snapQty(2.2, "cup"), 2.25);
  // Mass: coarse rungs for large amounts, fine ones for small.
  assert.equal(snapQty(133.3, "g"), 130);
  assert.equal(snapQty(1.6, "kg"), 1.6);
  // 25 is on the gram ladder and NOT on the millilitre one — 275 ml is not a
  // line on any jug, so this must land on 270.
  assert.equal(snapQty(266.6, "ml"), 270);
  assert.equal(snapQty(1.33, "l"), 1.3);
  // Imperial.
  assert.equal(snapQty(1.4, "lb"), 1.375);
  assert.equal(snapQty(3.3, "oz"), 3.25);
  assert.equal(snapQty(5.6, "fl_oz"), 5.5);
});

test("an eighth of a tablespoon is not on the ladder, because no tool has one", () => {
  // 1.6 Tbs would be 1⅝ if eighths were allowed. The coarsest rung within
  // tolerance would be the half, and 1.6 -> 1.5 is 6.25% — too far. So it
  // falls through to exact rather than inventing a measure.
  assert.equal(snapQty(1.6, "tbsp"), 1.6);
});

test("an integer is never moved", () => {
  // 24 g is measurable and 3 cups is measurable. Snapping removes values no
  // tool can express; it does not beautify values that are already fine.
  for (const [q, u] of [[24, "g"], [240, "ml"], [3, "cup"], [7, "tsp"], [333, "ml"]] as const)
    assert.equal(snapQty(q, u), q);
  // The one that would otherwise "helpfully" become 250.
  assert.equal(formatAmount(ing(120, "ml"), 2), "240 ml");
});

test("no rung within tolerance leaves the exact number alone", () => {
  // 0.3 cup is not near any cup measure: ⅓ is 11% away and ¼ is 17%. Honest
  // and unmeasurable beats pretty and wrong. (Expressing it as 5 Tbs is unit
  // conversion — a different feature; see ROADMAP.)
  assert.equal(snapQty(0.3, "cup"), 0.3);
  assert.equal(snapQty(0.3125, "cup"), 0.3125);
});

test("pinch and countable always snap, tolerance ignored", () => {
  // There is no such thing as 0.81 of an onion, or of a pinch.
  assert.equal(snapQty(2.81, null), 3);
  assert.equal(snapQty(1.5, "pinch"), 2);
  // Half an egg is real, though, so the countable ladder stops at halves
  // rather than at whole numbers.
  assert.equal(snapQty(4.5, null), 4.5);
  assert.equal(snapQty(4.4, null), 4.5);
});

test("a range takes one step for both ends", () => {
  // Snapped independently these would be 2¼ and 3⅓ — two denominators in one
  // amount, which reads like a mistake.
  assert.equal(formatAmount(ing(2, "cup", 3), 1.1), "2¼–3¼ cup");
  assert.equal(formatAmount(ing(100, "g", 200), 1.333), "130–270 g");
});

test("an unknown unit has no ladder and falls through to exact", () => {
  // The JSON hatch, or a future UNITS entry nobody added a ladder for. The
  // same defensive posture formatMinutes takes.
  assert.equal(snapQty(2.8125, "furlong" as Unit), 2.8125);
  assert.equal(formatAmount(ing(2.25, "furlong" as Unit), 1.25), "2.81 furlong");
});

test("snapQty leaves non-amounts alone", () => {
  for (const q of [0, -1, NaN, Infinity])
    assert.equal(Object.is(snapQty(q, "cup"), q), true);
});

test("editableAmount is exact, unscaled, and round-trips through parseAmount", () => {
  // The editor's contract, and the reason it is its own function. EditSheet
  // used to call formatAmount({ ...ing, unit: null }), and that nulled unit
  // selects the COUNTABLE ladder — one of the two that snap unconditionally.
  // The coincidence that kept rounding out of the box would have flipped to
  // corrupting it.
  for (const [qty, unit] of [
    [2.8125, "cup"], [133.3, "g"], [0.3, "cup"], [1 / 3, "cup"], [2.81, null],
  ] as Array<[number, Unit | null]>) {
    const shown = editableAmount(ing(qty, unit));
    assert.equal(shown.includes(" "), false, "no unit label belongs in the edit box");
    const back = parseAmount(shown).qty!;
    assert.ok(
      Math.abs(back - qty) <= 0.02,
      `${qty} ${unit} rendered "${shown}" and read back as ${back}`
    );
  }
  // There is no scale argument to pass, so nothing the diagram does reaches it.
  assert.equal(editableAmount(ing(null, "cup")), "");
  assert.equal(editableAmount({ ...ing(null, "cup"), text: "to taste" }), "to taste");
  assert.equal(editableAmount(ing(2, "cup", 3)), "2–3");
});
