// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/visual-redesign/CitrusKitchen.tsx": () => import("../components/mockups/visual-redesign/CitrusKitchen.tsx"),
  "./components/mockups/visual-redesign/Current.tsx": () => import("../components/mockups/visual-redesign/Current.tsx"),
  "./components/mockups/visual-redesign/InkAndPaper.tsx": () => import("../components/mockups/visual-redesign/InkAndPaper.tsx"),
  "./components/mockups/visual-redesign/LabNotebook.tsx": () => import("../components/mockups/visual-redesign/LabNotebook.tsx")
};
